// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXDgw39LmjHRkWwJ45imTWuw5yBO7dvNY',
    appId: '1:1052969738330:web:f39be9c5c7144b4e8a7863',
    messagingSenderId: '1052969738330',
    projectId: 'top-level-project-255b7',
    authDomain: 'top-level-project-255b7.firebaseapp.com',
    storageBucket: 'top-level-project-255b7.firebasestorage.app',
    measurementId: 'G-D62HPYTWL9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaR0_4EPn49zRZWvXojG5p69rPz-hpT5Y',
    appId: '1:1052969738330:android:ba00ee8bdd5b81538a7863',
    messagingSenderId: '1052969738330',
    projectId: 'top-level-project-255b7',
    storageBucket: 'top-level-project-255b7.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXDgw39LmjHRkWwJ45imTWuw5yBO7dvNY',
    appId: '1:1052969738330:web:f95a97d00206625b8a7863',
    messagingSenderId: '1052969738330',
    projectId: 'top-level-project-255b7',
    authDomain: 'top-level-project-255b7.firebaseapp.com',
    storageBucket: 'top-level-project-255b7.firebasestorage.app',
    measurementId: 'G-REMEKL3N08',
  );
}
